### ISSUE TITLE
Incompatible with MultiJob View

### ISSUE THREAD

**Issue by arpitgold** [rackerlabs/canon-jenkins#18]
We are using MultiJob Plugin with our Jenkins Jobs.
When I try to view my job with MultiJob plugin. It is showing breking UI.
In multiJob view status is the 2nd column not the 1st column.
Can we add any stylesheet to make it compatible.
![2](https://cloud.githubusercontent.com/assets/5267739/8053002/31632dee-0eaa-11e5-81ca-71dbb1cc32a0.png)

**Comment by bighappyface** [comment]
@arpitgold the canon jenkins style overrides are meant for vanilla jenkins installations. It is difficult to style all plugins, or even jenkins itself, with so many changes occurring so frequently.

For the multijob project issues, I am happy to review a PR submission with new styles to make it work. Otherwise, it may be best to use the default styling for Jenkins.

**Comment by arpitgold** [comment]
Hi @bighappyface ,

I have created a MR on MultiJob Plugin : https://github.com/jenkinsci/tikal-multijob-plugin/pull/67
This MR is accepted. It will fixed in there next release.
Thanks for you quick response and support.

**Comment by bighappyface** [comment]
@arpitgold thank you for the update!
